### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by Jakob-SD** [aidanchandra/ZeroTierCortana#2]
Hi

I get error 

```
Launch error
See the py2app website for debugging launch issues
```

after submitting api key and network id.

> /Applications/ZeroTier Cortana.app/Contents/Resources/__boot__.py:116: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/main.py", line 137, in <module>
    app = ZeroTierApp()
          ^^^^^^^^^^^^^
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/main.py", line 16, in __init__
    self.update_members(None)
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/main.py", line 55, in update_members
    members = self.get_network_members()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ZeroTier Cortana.app/Contents/Resources/main.py", line 126, in get_network_members
    conn = http.client.HTTPSConnection("my.zerotier.com")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'http.client' has no attribute 'HTTPSConnection'. Did you mean: 'HTTPConnection'?
2023-10-09 21:03:53.495 ZeroTier Cortana[25759:546295] Launch error
2023-10-09 21:03:53.495 ZeroTier Cortana[25759:546295] Launch error
See the py2app website for debugging launch issues

**Comment by aidanchandra** [comment]
Interesting. Can you pls send me the result of `pip freeze`. py2app should package everything w/o pip, but I'm curious.
There might be a version mismatch that pip freeze could reveal.

**Comment by Jakob-SD** [comment]
I don't have `pip` but only `pip3`. Could that be the issue?

> jakob@Jakobs-Air ~ % pip3 freeze
aigpy==2022.7.8.1
aiodns==3.0.0
aiofiles==0.7.0
aiohttp==3.8.5
aiosignal==1.3.1
appdirs==1.4.4
async-timeout==4.0.3
attrs==23.1.0
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.2.0
cleo==1.0.0a4
click==8.1.7
colorama==0.4.6
crashtest==0.3.1
deezer-py==1.3.6
frozenlist==1.4.0
idna==3.4
iso8601==2.1.0
m3u8==0.9.0
multidict==6.0.4
mutagen==1.47.0
pathvalidate==2.5.2
Pillow==9.5.0
prettytable==3.8.0
pycares==4.3.0
pycparser==2.21
pycryptodome==3.18.0
pycryptodomex==3.19.0
pydub==0.25.1
pylev==1.4.0
requests==2.31.0
simple-term-menu==1.6.1
six==1.16.0
streamrip==1.9.7
tidal-dl==2022.10.31.1
tomlkit==0.7.2
tqdm==4.66.1
urllib3==2.0.4
wcwidth==0.2.6
yarl==1.9.2

**Comment by aidanchandra** [comment]
Can't believe I dropped this. Still facing this issue?

**Comment by Jakob-SD** [comment]
Yes same error on launch

**Comment by aidanchandra** [comment]
Better embarrassingly late than never. Apologies.

Try this command:

`pip install --upgrade certifi`

I tried to replicate your issue but couldn't reproduce it.
